server:
  port: 10086
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://114.116.7.143:1433;database=POSHINGSWR
    username: sa
    password: 19970603
  aop:
    auto: true
    proxy-target-class: true
#日志配置 无特殊需求无需更改
logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG
mybatis-plus:
  mapper-locations: classpath:com/poshing/swr/mapper/**.xml
  type-aliases-package: com.poshing.swr.entity
  configuration:
    jdbc-type-for-null: VARCHAR
  #配置JdbcTypeForNull, oracle数据库必须配置